test_dataset:
  dataset:
    name: paired-image-folders
    args:
      # root_path_1: ./load/BSD_100_X2/LR
      # root_path_2: ./load/BSD_100_X2/GT
      root_path_1: ./load/SET_14_X2/LR
      root_path_2: ./load/SET_14_X2/GT
      # root_path_1: ./load/Urban_100_X2/LR
      # root_path_2: ./load/Urban_100_X2/GT

  wrapper:
    name: sr-implicit-paired
    args: {}
  batch_size: 1
eval_type: div2k-2
eval_bsize: 30000

data_norm:
  inp: {sub: [0.5], div: [0.5]}
  gt: {sub: [0.5], div: [0.5]}